### ISSUE TITLE
Docker does not copy all required files on windows.

### ISSUE THREAD

**Issue by RaphaelWoude** [geospiza-fortis/argonms-server#13]
Starting the environment with docker on windows will not copy over all the required files, such as WZ, scripts and bin.
On linux on the otherhand, it does copy over all the required files. I have no idea why this is happening.

**Comment by geospiza-fortis** [comment]
Can you expand on this? Make sure you have a valid `.env` file in the root of the repository, and you have set the `DATA_DIR` to point to the WZ files that have been [compiled to KVJ](https://github.com/geospiza-fortis/argonms-data/tree/docker).

What errors do you get?

**Comment by RaphaelWoude** [comment]
After some debugging I found that windows was holding on to some of the files for whatever reason. A reboot fixed the problem but then there were line ending problems. So I used your fix in the README.md and everything works fine now.
